name: airbyte_utils
version: '1.0'
config-version: 2
profile: normalize
model-paths:
- models
docs-paths:
- docs
analysis-paths:
- analysis
test-paths:
- tests
seed-paths:
- data
macro-paths:
- macros

target-path: "../build"  # directory which will store compiled SQL files
log-path: "../logs"  # directory which will store DBT logs
packages-install-path: "../dbt-packages"

quoting:
  database: true
  schema: false
  identifier: true

models:
  airbyte_utils:
    +materialized: table
    0_ctes:
      +tags: 
      - cta
      materialized: ephemeral
    1_cta_base_tables:
      +tags: 
      - cta
      +materialized: table
      +on_schema_change: sync_all_columns

dispatch:
- macro_namespace: dbt_utils
  search_order:
  - airbyte_utils
  - dbt_utils
vars:
  json_column: _airbyte_data
  models_to_source:
    managed_form_contributions_stream_ab1: mailchimp._airbyte_raw_managed_form_contributions_stream
    managed_form_contributions_stream_ab2: mailchimp._airbyte_raw_managed_form_contributions_stream
    managed_form_contributions_stream_ab3: mailchimp._airbyte_raw_managed_form_contributions_stream
    managed_form_contributions_stream: mailchimp._airbyte_raw_managed_form_contributions_stream
    paid_contributions_stream_ab1: mailchimp._airbyte_raw_paid_contributions_stream
    paid_contributions_stream_ab2: mailchimp._airbyte_raw_paid_contributions_stream
    paid_contributions_stream_ab3: mailchimp._airbyte_raw_paid_contributions_stream
    paid_contributions_stream: mailchimp._airbyte_raw_paid_contributions_stream
    refunded_contributions_stream_ab1: mailchimp._airbyte_raw_refunded_contributions_stream
    refunded_contributions_stream_ab2: mailchimp._airbyte_raw_refunded_contributions_stream
    refunded_contributions_stream_ab3: mailchimp._airbyte_raw_refunded_contributions_stream
    refunded_contributions_stream: mailchimp._airbyte_raw_refunded_contributions_stream
