config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    dev-cta:
        dataset: mailchimp
        location: US
        method: oauth
        priority: interactive
        project: dev3869c056
        retries: 3
        threads: 8
        type: bigquery
