version: 2
sources:
- name: mailchimp
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_managed_form_contributions_stream
  - name: _airbyte_raw_paid_contributions_stream
  - name: _airbyte_raw_refunded_contributions_stream
