version: 2
sources:
- name: mailchimp
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_campaigns
  - name: _airbyte_raw_email_activity
  - name: _airbyte_raw_lists
